import type { GalaxyModule } from '../types'

export const moduleDefinitions: GalaxyModule[] = [
  { id: 'video-studio', translationKey: 'videoStudio', name: 'Video Studio', shortName: 'VIDEO', description: 'AI-assisted video workflow and automated editing.', status: 'AVAILABLE / PROTOTYPE', available: true, theme: 'azure', position: [19, 34], scale: 1.25, route: '/video-studio', icon: '◉', accent: '#9cbbff', featureNodes: ['Video', 'Audio', 'Subtitle', 'Music', 'Logo', 'AI Analysis'] },
  { id: 'production', translationKey: 'production', name: 'AI Production Studio', shortName: 'PRODUCTION', description: 'AI image and video generation workflow.', status: 'COMING SOON', available: false, theme: 'violet', position: [78, 28], scale: 1, route: '/production', icon: '✦', accent: '#bba1ff', featureNodes: [] },
  { id: 'all-brain', translationKey: 'allBrain', name: 'ALL Brain', shortName: 'BRAIN', description: 'Cross-industry knowledge, prompts and templates.', status: 'COMING SOON', available: false, theme: 'cyan', position: [86, 62], scale: .9, route: '/brain', icon: '◌', accent: '#85d6e8', featureNodes: [] },
  { id: 'cloud', translationKey: 'cloud', name: 'Ernest Cloud', shortName: 'CLOUD', description: 'Automated order, processing and delivery platform.', status: 'COMING SOON', available: false, theme: 'blue', position: [66, 78], scale: .85, route: '/cloud', icon: '△', accent: '#8faeff', featureNodes: [] },
  { id: 'academy', translationKey: 'academy', name: 'AI Academy', shortName: 'ACADEMY', description: 'AI learning and course management.', status: 'COMING SOON', available: false, theme: 'gold', position: [35, 80], scale: .82, route: '/academy', icon: '◇', accent: '#c4b7f0', featureNodes: [] },
  { id: 'stock', translationKey: 'stock', name: 'Stock Research Hub', shortName: 'RESEARCH', description: 'Market research and automated briefings.', status: 'COMING SOON', available: false, theme: 'aqua', position: [10, 65], scale: .84, route: '/research', icon: '⌁', accent: '#8ebee4', featureNodes: [] },
  { id: 'family', translationKey: 'family', name: 'Family Learning', shortName: 'LEARNING', description: 'Immersive English learning for children.', status: 'COMING SOON', available: false, theme: 'rose', position: [11, 19], scale: .82, route: '/learning', icon: '○', accent: '#d6a8dc', featureNodes: [] },
  { id: 'life', translationKey: 'life', name: 'E.X Life OS', shortName: 'LIFE OS', description: 'Time, health, finance and life planning.', status: 'COMING SOON', available: false, theme: 'silver', position: [47, 13], scale: .78, route: '/life', icon: '⊹', accent: '#c4d1ea', featureNodes: [] },
]
