import type { TranslationDictionary } from '../localeTypes'

export const en: TranslationDictionary = {
  'loading.aria': 'Initializing E.X Galaxy', 'loading.initializing': 'INITIALIZING E.X GALAXY', 'loading.percent': '{value} percent initialized',
  'loading.status.calibrating': 'CALIBRATING STARFIELD', 'loading.status.core': 'LOADING GALAXY CORE', 'loading.status.modules': 'CONNECTING AI MODULES', 'loading.status.sync': 'SYNCHRONIZING SYSTEM', 'loading.status.ready': 'SYSTEM READY',
  'idle.kicker': 'AI CREATIVE OPERATING SYSTEM', 'idle.prototype': 'PROTOTYPE v1.2 · SHOWCASE+', 'idle.enter': 'CLICK TO ENTER', 'idle.enterAria': 'Enter E.X Galaxy',
  'activation.systemActivating': 'SYSTEM ACTIVATING', 'activation.connecting': 'ENERGY RING SYNCHRONIZING', 'activation.systemOnline': 'SYSTEM ONLINE', 'activation.fullyConnected': 'FULLY CONNECTED',
  'nav.home': 'HOME', 'nav.projects': 'PROJECTS', 'nav.assets': 'ASSETS', 'nav.campaigns': 'CAMPAIGNS', 'nav.studio': 'STUDIO', 'nav.language': 'Language selector', 'nav.quality': 'Quality mode', 'nav.motion': 'Toggle motion', 'nav.motionOn': 'MOTION ON', 'nav.motionOff': 'MOTION OFF', 'nav.presentation': 'PRESENTATION MODE', 'nav.credits': '{value} CREDITS', 'nav.account': 'Account and membership',
  'home.kicker': 'AI CREATIVE OPERATING SYSTEM', 'home.prototype': 'PROTOTYPE v1.2 · SHOWCASE+',
  'cards.aria': 'Featured concept projects', 'cards.film': 'FILM', 'cards.ai': 'AI', 'cards.campaign': 'CAMPAIGN', 'cards.reel': 'REEL', 'cards.audio': 'AUDIO', 'cards.luxury': 'Luxury Real Estate Film', 'cards.visual': 'AI Visual Campaign', 'cards.brand': 'Brand Campaign', 'cards.city': 'City Lights Reel', 'cards.soundtrack': 'Cinematic Soundtrack',
  'cta.newCampaign': 'NEW CAMPAIGN', 'cta.openProject': 'OPEN PROJECT', 'cta.mediaLibrary': 'MEDIA LIBRARY', 'status.activeProjects': '{value} ACTIVE PROJECTS', 'status.online': 'GALAXY STUDIO ONLINE',
  'module.preview': 'MODULE PREVIEW', 'module.comingSoon': 'COMING SOON', 'module.return': 'RETURN TO GALAXY', 'module.back': 'BACK TO GALAXY', 'module.backAria': 'Back to Galaxy',
  'modules.videoStudio.name': 'Video Studio', 'modules.videoStudio.description': 'AI-assisted video workflow and automated editing.', 'modules.production.name': 'AI Production Studio', 'modules.production.description': 'AI image and video generation workflow.', 'modules.allBrain.name': 'ALL Brain', 'modules.allBrain.description': 'Cross-industry knowledge, prompts and templates.', 'modules.cloud.name': 'Ernest Cloud', 'modules.cloud.description': 'Automated order, processing and delivery platform.', 'modules.academy.name': 'AI Academy', 'modules.academy.description': 'AI learning and course management.', 'modules.stock.name': 'Stock Research Hub', 'modules.stock.description': 'Market research and automated briefings.', 'modules.family.name': 'Family Learning', 'modules.family.description': 'Immersive English learning for children.', 'modules.life.name': 'E.X Life OS', 'modules.life.description': 'Time, health, finance and life planning.',
  'video.header': 'VIDEO STUDIO / AUTOPILOT', 'video.title': 'CREATIVE ORBIT', 'video.standby': 'SYSTEM STANDING BY', 'video.processing': 'PROCESSING', 'video.complete': 'COMPLETE', 'video.ready': 'READY', 'video.start': 'START AUTO CREATE', 'video.startAria': 'Start Auto Create', 'video.drop': 'DROP MEDIA OR START', 'video.mediaReady': 'MEDIA READY', 'video.qualityPassed': 'QUALITY CHECK PASSED', 'video.orbit': 'DRAG MEDIA INTO ORBIT', 'video.assetsInOrbit': '{value}/8 ASSETS IN ORBIT', 'video.timeline': 'AI TIMELINE / BUILDING', 'video.videoTrack': 'VIDEO TRACK', 'video.audioTrack': 'AUDIO TRACK', 'video.subtitleTrack': 'SUBTITLE TRACK', 'video.overlayTrack': 'LOGO / OVERLAY', 'video.preview': 'PREVIEW DEMO', 'video.export': 'EXPORT DEMO', 'video.exported': 'EXPORT COMPLETED', 'video.back': 'BACK TO GALAXY', 'video.fast': 'FAST COMPLETE', 'video.summary': '9:16 · Subtitles Completed · Music Matched · Transitions Applied · Logo Added · Quality Check Passed',
  'workflow.0': 'Scanning media', 'workflow.1': 'Detecting scenes', 'workflow.2': 'Classifying content', 'workflow.3': 'Analyzing visual quality', 'workflow.4': 'Building story structure', 'workflow.5': 'Selecting best shots', 'workflow.6': 'Creating timeline', 'workflow.7': 'Generating subtitles', 'workflow.8': 'Matching soundtrack', 'workflow.9': 'Applying transitions', 'workflow.10': 'Adding logo', 'workflow.11': 'Running quality check', 'workflow.12': 'Project ready',
  'presentation.initializing': 'INITIALIZING', 'presentation.pause': 'PAUSE', 'presentation.resume': 'RESUME', 'presentation.restart': 'RESTART', 'presentation.skip': 'SKIP STEP', 'presentation.fullscreen': 'FULLSCREEN', 'presentation.exit': 'EXIT DEMO', 'presentation.chapter.0': 'DEEP SPACE', 'presentation.chapter.1': 'A GALAXY FOR CREATION', 'presentation.chapter.2': 'SYSTEM AWAKENING', 'presentation.chapter.3': 'VIDEO STUDIO', 'presentation.chapter.4': 'AUTO CREATE', 'presentation.chapter.5': 'PROJECT READY', 'presentation.chapter.6': 'EXPORT COMPLETED', 'presentation.chapter.7': 'ONE GALAXY. EVERY AI WORKFLOW.',
  'account.title': 'ACCOUNT CONSOLE', 'account.guest': 'GUEST ACCESS', 'account.member': 'MEMBER PROFILE', 'account.signIn': 'SIGN IN', 'account.create': 'CREATE ACCOUNT', 'account.signOut': 'SIGN OUT', 'account.settings': 'SETTINGS', 'account.currentPlan': 'CURRENT PLAN', 'account.upgrade': 'UPGRADE PLAN', 'account.close': 'Close panel', 'account.mock': 'SHOWCASE MODE · NO LIVE ACCOUNT',
  'credits.title': 'E.X CREDITS', 'credits.balance': 'CURRENT BALANCE', 'credits.monthly': 'MONTHLY ALLOCATION', 'credits.usage': 'USAGE THIS MONTH', 'credits.activity': 'RECENT ACTIVITY', 'credits.buy': 'BUY CREDITS', 'credits.upgrade': 'UPGRADE PLAN', 'credits.demo': 'DEMO / COMING SOON', 'credits.buyNotice': 'Credit purchase is available in demo mode only.',
  'plans.title': 'LICENSE CONSOLE', 'plans.preview': 'PRICING PREVIEW', 'plans.free': 'FREE', 'plans.creator': 'CREATOR', 'plans.enterprise': 'ENTERPRISE', 'plans.freeTagline': 'Explore E.X Galaxy', 'plans.creatorTagline': 'For individual creators & professionals', 'plans.enterpriseTagline': 'For teams & organizations', 'plans.freePrice': 'Free', 'plans.creatorPrice': 'Coming Soon', 'plans.enterprisePrice': 'Contact Us', 'plans.current': 'CURRENT PLAN', 'plans.request': 'REQUEST ACCESS', 'plans.contact': 'CONTACT ENTERPRISE',
  'plans.free.1': 'Basic Galaxy Access', 'plans.free.2': 'Demo modules', 'plans.free.3': 'Basic workflow', 'plans.free.4': 'Limited monthly credits', 'plans.creator.1': 'Higher monthly credits', 'plans.creator.2': 'Advanced AI workflows', 'plans.creator.3': 'Premium Video Studio', 'plans.creator.4': 'Future cloud sync', 'plans.enterprise.1': 'Team workspace', 'plans.enterprise.2': 'Shared credits', 'plans.enterprise.3': 'Admin controls', 'plans.enterprise.4': 'Private deployment',
  'enterprise.title': 'ENTERPRISE FOUNDATION', 'enterprise.description': 'A private operating layer for teams, organizations, and custom AI workflows.', 'enterprise.team': 'Team Workspace', 'enterprise.sharedCredits': 'Shared Credits', 'enterprise.admin': 'Organization Admin', 'enterprise.roles': 'Permission Roles', 'enterprise.workflow': 'Custom AI Workflow', 'enterprise.library': 'Private Asset Library', 'enterprise.api': 'API / Integration', 'enterprise.deployment': 'Private Deployment', 'enterprise.support': 'Dedicated Support', 'enterprise.company': 'Company', 'enterprise.name': 'Name', 'enterprise.email': 'Email', 'enterprise.teamSize': 'Team Size', 'enterprise.useCase': 'Use Case', 'enterprise.submit': 'CONTACT ENTERPRISE', 'enterprise.captured': 'Request captured in demo mode.', 'enterprise.placeholderCompany': 'Organization name', 'enterprise.placeholderName': 'Display name', 'enterprise.placeholderEmail': 'name@company.com', 'enterprise.placeholderTeam': 'e.g. 20–50', 'enterprise.placeholderUseCase': 'How could E.X Galaxy support the team?',
  'common.close': 'CLOSE', 'common.comingSoon': 'COMING SOON', 'common.demo': 'DEMO MODE', 'common.contact': 'CONTACT US',
}
