import { en } from './en'
import type { TranslationDictionary } from '../localeTypes'

export const ja: TranslationDictionary = { ...en,
  'activation.systemActivating': 'システム起動中', 'activation.connecting': 'エネルギーリングを同期中', 'activation.systemOnline': 'システムオンライン', 'activation.fullyConnected': 'すべて接続済み',
  'loading.initializing': 'E.X GALAXY を初期化中', 'loading.percent': '{value}% 初期化完了', 'loading.status.calibrating': 'スターフィールドを調整中', 'loading.status.core': 'ギャラクシーコアを読み込み中', 'loading.status.modules': 'AI モジュールを接続中', 'loading.status.sync': 'システムを同期中', 'loading.status.ready': 'システム準備完了',
  'idle.kicker': 'AI クリエイティブ・オペレーティング・システム', 'idle.enter': 'クリックして入る', 'idle.enterAria': 'E.X Galaxy に入る', 'nav.home': 'ホーム', 'nav.projects': 'プロジェクト', 'nav.assets': 'アセット', 'nav.campaigns': 'キャンペーン', 'nav.studio': 'スタジオ', 'nav.language': '言語選択', 'nav.quality': '品質モード', 'nav.motion': 'モーション切替', 'nav.motionOn': 'モーション ON', 'nav.motionOff': 'モーション OFF', 'nav.presentation': 'プレゼンテーション', 'nav.credits': '{value} クレジット', 'nav.account': 'アカウントとプラン',
  'cta.newCampaign': '新規キャンペーン', 'cta.openProject': 'プロジェクトを開く', 'cta.mediaLibrary': 'メディアライブラリ', 'status.activeProjects': 'アクティブなプロジェクト {value} 件', 'status.online': 'GALAXY STUDIO オンライン', 'module.preview': 'モジュールプレビュー', 'module.comingSoon': '近日公開', 'module.return': 'ギャラクシーへ戻る', 'module.back': 'ギャラクシーへ戻る', 'module.backAria': 'ギャラクシーへ戻る',
  'video.title': 'クリエイティブ・オービット', 'video.standby': 'システム待機中', 'video.processing': '処理中', 'video.complete': '完了', 'video.ready': '準備完了', 'video.start': 'AUTO CREATE を開始', 'video.drop': 'メディアをドロップまたは開始', 'video.mediaReady': 'メディア準備完了', 'video.qualityPassed': '品質チェック完了', 'video.orbit': 'メディアを軌道へドラッグ', 'video.assetsInOrbit': '軌道上のアセット {value}/8', 'video.timeline': 'AI タイムライン／構築中', 'video.videoTrack': 'ビデオトラック', 'video.audioTrack': 'オーディオトラック', 'video.subtitleTrack': '字幕トラック', 'video.overlayTrack': 'ロゴ／オーバーレイ', 'video.preview': 'デモをプレビュー', 'video.export': 'エクスポートデモ', 'video.exported': 'エクスポート完了', 'video.back': 'ギャラクシーへ戻る', 'video.fast': '高速完了',
  'presentation.initializing': '初期化中', 'presentation.pause': '一時停止', 'presentation.resume': '再開', 'presentation.restart': '再開する', 'presentation.skip': 'ステップをスキップ', 'presentation.fullscreen': '全画面', 'presentation.exit': 'デモを終了',
  'account.title': 'アカウントコンソール', 'account.guest': 'ゲストアクセス', 'account.member': 'メンバープロフィール', 'account.signIn': 'サインイン', 'account.create': 'アカウント作成', 'account.signOut': 'サインアウト', 'account.settings': '設定', 'account.currentPlan': '現在のプラン', 'account.upgrade': 'プランをアップグレード', 'account.close': 'パネルを閉じる', 'account.mock': 'ショーケースモード · ライブアカウントではありません',
  'credits.title': 'E.X クレジット', 'credits.balance': '現在の残高', 'credits.monthly': '月間配分', 'credits.usage': '今月の使用量', 'credits.activity': '最近のアクティビティ', 'credits.buy': 'クレジットを購入', 'credits.upgrade': 'プランをアップグレード', 'credits.demo': 'デモ / 近日公開', 'credits.buyNotice': 'クレジット購入はデモモードのみです。',
  'plans.title': 'ライセンスコンソール', 'plans.preview': '料金プレビュー', 'plans.freeTagline': 'E.X Galaxy を体験', 'plans.creatorTagline': '個人クリエイターとプロフェッショナル向け', 'plans.enterpriseTagline': 'チームと組織向け', 'plans.freePrice': '無料', 'plans.creatorPrice': '近日公開', 'plans.enterprisePrice': 'お問い合わせ', 'plans.current': '現在のプラン', 'plans.request': 'アクセスをリクエスト', 'plans.contact': 'エンタープライズに連絡',
  'enterprise.title': 'エンタープライズ基盤', 'enterprise.description': 'チーム、組織、カスタム AI ワークフローのためのプライベート運用レイヤー。', 'enterprise.team': 'チームワークスペース', 'enterprise.sharedCredits': '共有クレジット', 'enterprise.admin': '組織管理', 'enterprise.roles': '権限ロール', 'enterprise.workflow': 'カスタム AI ワークフロー', 'enterprise.library': 'プライベートアセットライブラリ', 'enterprise.api': 'API / 連携', 'enterprise.deployment': 'プライベートデプロイ', 'enterprise.support': '専任サポート', 'enterprise.company': '会社', 'enterprise.name': '名前', 'enterprise.email': 'メール', 'enterprise.teamSize': 'チーム規模', 'enterprise.useCase': 'ユースケース', 'enterprise.submit': 'エンタープライズに連絡', 'enterprise.captured': 'リクエストはデモモードで受け付けました。', 'common.close': '閉じる', 'common.comingSoon': '近日公開', 'common.demo': 'デモモード', 'common.contact': 'お問い合わせ',
}
