import { en } from './en'
import type { TranslationDictionary } from '../localeTypes'

export const ko: TranslationDictionary = { ...en,
  'activation.systemActivating': '시스템 활성화 중', 'activation.connecting': '에너지 링 동기화 중', 'activation.systemOnline': '시스템 온라인', 'activation.fullyConnected': '완전히 연결됨',
  'loading.initializing': 'E.X GALAXY 초기화 중', 'loading.percent': '{value}% 초기화됨', 'loading.status.calibrating': '스타필드 보정 중', 'loading.status.core': '갤럭시 코어 로딩 중', 'loading.status.modules': 'AI 모듈 연결 중', 'loading.status.sync': '시스템 동기화 중', 'loading.status.ready': '시스템 준비 완료',
  'idle.kicker': 'AI 크리에이티브 운영체제', 'idle.enter': '클릭하여 입장', 'idle.enterAria': 'E.X Galaxy 입장', 'nav.home': '홈', 'nav.projects': '프로젝트', 'nav.assets': '에셋', 'nav.campaigns': '캠페인', 'nav.studio': '스튜디오', 'nav.language': '언어 선택', 'nav.quality': '품질 모드', 'nav.motion': '모션 전환', 'nav.motionOn': '모션 켜짐', 'nav.motionOff': '모션 꺼짐', 'nav.presentation': '프레젠테이션 모드', 'nav.credits': '{value} 크레딧', 'nav.account': '계정 및 멤버십',
  'cta.newCampaign': '새 캠페인', 'cta.openProject': '프로젝트 열기', 'cta.mediaLibrary': '미디어 라이브러리', 'status.activeProjects': '활성 프로젝트 {value}개', 'status.online': 'GALAXY STUDIO 온라인', 'module.preview': '모듈 미리보기', 'module.comingSoon': '출시 예정', 'module.return': '갤럭시로 돌아가기', 'module.back': '갤럭시로 돌아가기', 'module.backAria': '갤럭시로 돌아가기',
  'video.title': '크리에이티브 오빗', 'video.standby': '시스템 대기 중', 'video.processing': '처리 중', 'video.complete': '완료', 'video.ready': '준비됨', 'video.start': 'AUTO CREATE 시작', 'video.drop': '미디어를 놓거나 시작', 'video.mediaReady': '미디어 준비 완료', 'video.qualityPassed': '품질 검사 통과', 'video.orbit': '미디어를 오빗으로 드래그', 'video.assetsInOrbit': '오빗 내 에셋 {value}/8', 'video.timeline': 'AI 타임라인 / 구축 중', 'video.videoTrack': '비디오 트랙', 'video.audioTrack': '오디오 트랙', 'video.subtitleTrack': '자막 트랙', 'video.overlayTrack': '로고 / 오버레이', 'video.preview': '데모 미리보기', 'video.export': '데모 내보내기', 'video.exported': '내보내기 완료', 'video.back': '갤럭시로 돌아가기', 'video.fast': '빠른 완료',
  'presentation.initializing': '초기화 중', 'presentation.pause': '일시정지', 'presentation.resume': '계속', 'presentation.restart': '다시 시작', 'presentation.skip': '단계 건너뛰기', 'presentation.fullscreen': '전체 화면', 'presentation.exit': '데모 나가기',
  'account.title': '계정 콘솔', 'account.guest': '게스트 액세스', 'account.member': '멤버 프로필', 'account.signIn': '로그인', 'account.create': '계정 만들기', 'account.signOut': '로그아웃', 'account.settings': '설정', 'account.currentPlan': '현재 플랜', 'account.upgrade': '플랜 업그레이드', 'account.close': '패널 닫기', 'account.mock': '쇼케이스 모드 · 실제 계정 없음',
  'credits.title': 'E.X 크레딧', 'credits.balance': '현재 잔액', 'credits.monthly': '월간 할당량', 'credits.usage': '이번 달 사용량', 'credits.activity': '최근 활동', 'credits.buy': '크레딧 구매', 'credits.upgrade': '플랜 업그레이드', 'credits.demo': '데모 / 출시 예정', 'credits.buyNotice': '크레딧 구매는 데모 모드에서만 제공됩니다.',
  'plans.title': '라이선스 콘솔', 'plans.preview': '가격 미리보기', 'plans.freeTagline': 'E.X Galaxy 탐색', 'plans.creatorTagline': '개인 크리에이터와 전문가를 위한', 'plans.enterpriseTagline': '팀과 조직을 위한', 'plans.freePrice': '무료', 'plans.creatorPrice': '출시 예정', 'plans.enterprisePrice': '문의하기', 'plans.current': '현재 플랜', 'plans.request': '액세스 요청', 'plans.contact': '엔터프라이즈 문의',
  'enterprise.title': '엔터프라이즈 기반', 'enterprise.description': '팀, 조직 및 맞춤 AI 워크플로우를 위한 비공개 운영 레이어.', 'enterprise.team': '팀 워크스페이스', 'enterprise.sharedCredits': '공유 크레딧', 'enterprise.admin': '조직 관리', 'enterprise.roles': '권한 역할', 'enterprise.workflow': '맞춤 AI 워크플로우', 'enterprise.library': '비공개 에셋 라이브러리', 'enterprise.api': 'API / 통합', 'enterprise.deployment': '비공개 배포', 'enterprise.support': '전담 지원', 'enterprise.company': '회사', 'enterprise.name': '이름', 'enterprise.email': '이메일', 'enterprise.teamSize': '팀 규모', 'enterprise.useCase': '사용 사례', 'enterprise.submit': '엔터프라이즈 문의', 'enterprise.captured': '요청이 데모 모드에 기록되었습니다.', 'common.close': '닫기', 'common.comingSoon': '출시 예정', 'common.demo': '데모 모드', 'common.contact': '문의하기',
}
