import { en } from './en'
import type { TranslationDictionary } from '../localeTypes'

export const zhTW: TranslationDictionary = { ...en,
  'activation.systemActivating': '系統啟動中', 'activation.connecting': '能量環同步中', 'activation.systemOnline': '系統已上線', 'activation.fullyConnected': '完整連結',
  'loading.initializing': '正在初始化 E.X GALAXY', 'loading.percent': '已初始化 {value}%', 'loading.status.calibrating': '校準星場中', 'loading.status.core': '載入銀河核心中', 'loading.status.modules': '連接 AI 模組中', 'loading.status.sync': '同步系統中', 'loading.status.ready': '系統就緒',
  'idle.kicker': 'AI 創意作業系統', 'idle.prototype': 'PROTOTYPE v1.2 · 展示預覽', 'idle.enter': '點擊進入', 'idle.enterAria': '進入 E.X Galaxy',
  'nav.home': '首頁', 'nav.projects': '專案', 'nav.assets': '素材', 'nav.campaigns': '活動', 'nav.studio': '工作室', 'nav.language': '語言選擇', 'nav.quality': '品質模式', 'nav.motion': '切換動態', 'nav.motionOn': '動態開啟', 'nav.motionOff': '動態關閉', 'nav.presentation': '展示模式', 'nav.credits': '{value} 點數', 'nav.account': '帳戶與方案',
  'home.kicker': 'AI 創意作業系統', 'home.prototype': 'PROTOTYPE v1.2 · 展示預覽', 'cards.aria': '精選概念專案', 'cards.luxury': '精品房地產影片', 'cards.visual': 'AI 視覺企劃', 'cards.brand': '品牌企劃', 'cards.city': '城市光影短片', 'cards.soundtrack': '電影感配樂',
  'cta.newCampaign': '新增活動', 'cta.openProject': '開啟專案', 'cta.mediaLibrary': '媒體資料庫', 'status.activeProjects': '{value} 個進行中專案', 'status.online': '銀河工作室已上線',
  'module.preview': '模組預覽', 'module.comingSoon': '即將推出', 'module.return': '返回銀河', 'module.back': '返回銀河', 'module.backAria': '返回銀河',
  'modules.videoStudio.description': 'AI 輔助影音工作流與自動剪輯。', 'modules.production.description': 'AI 圖像與影片生成工作流。', 'modules.allBrain.description': '跨產業知識、提示詞與範本。', 'modules.cloud.description': '自動化訂單、處理與交付平台。', 'modules.academy.description': 'AI 學習與課程管理。', 'modules.stock.description': '市場研究與自動化簡報。', 'modules.family.description': '兒童沉浸式英文學習。', 'modules.life.description': '時間、健康、財務與生活規劃。',
  'video.title': '創意軌道', 'video.standby': '系統待命中', 'video.processing': '處理中', 'video.complete': '已完成', 'video.ready': '就緒', 'video.start': '啟動自動建立', 'video.drop': '拖入素材或開始', 'video.mediaReady': '素材已就緒', 'video.qualityPassed': '品質檢查通過', 'video.orbit': '將素材拖入軌道', 'video.assetsInOrbit': '軌道中 {value} 個素材', 'video.timeline': 'AI 時間軸／建立中', 'video.videoTrack': '影片軌', 'video.audioTrack': '音訊軌', 'video.subtitleTrack': '字幕軌', 'video.overlayTrack': '標誌／覆蓋軌', 'video.preview': '預覽展示', 'video.export': '模擬輸出', 'video.exported': '輸出完成', 'video.back': '返回銀河', 'video.fast': '快速完成', 'video.summary': '9:16 · 字幕完成 · 音樂已配對 · 轉場已套用 · 標誌已加入 · 品質檢查通過',
  'workflow.0': '掃描素材', 'workflow.1': '偵測場景', 'workflow.2': '分類內容', 'workflow.3': '分析畫面品質', 'workflow.4': '建立故事結構', 'workflow.5': '挑選最佳鏡頭', 'workflow.6': '建立時間軸', 'workflow.7': '產生字幕', 'workflow.8': '配對配樂', 'workflow.9': '套用轉場', 'workflow.10': '加入標誌', 'workflow.11': '執行品質檢查', 'workflow.12': '專案完成',
  'presentation.initializing': '初始化中', 'presentation.pause': '暫停', 'presentation.resume': '繼續', 'presentation.restart': '重新播放', 'presentation.skip': '跳過步驟', 'presentation.fullscreen': '全螢幕', 'presentation.exit': '離開展示', 'presentation.chapter.0': '深空', 'presentation.chapter.1': '為創作而生的銀河', 'presentation.chapter.2': '系統甦醒', 'presentation.chapter.4': '自動建立', 'presentation.chapter.5': '專案完成', 'presentation.chapter.6': '輸出完成', 'presentation.chapter.7': '一座銀河，承載每一個 AI 工作流。',
  'account.title': '帳戶控制台', 'account.guest': '訪客存取', 'account.member': '會員檔案', 'account.signIn': '模擬登入', 'account.create': '建立帳戶', 'account.signOut': '模擬登出', 'account.settings': '設定', 'account.currentPlan': '目前方案', 'account.upgrade': '升級方案', 'account.close': '關閉面板', 'account.mock': '展示模式 · 非正式帳戶',
  'credits.title': 'E.X 點數', 'credits.balance': '目前餘額', 'credits.monthly': '每月配額', 'credits.usage': '本月使用量', 'credits.activity': '近期活動', 'credits.buy': '購買點數', 'credits.upgrade': '升級方案', 'credits.demo': '展示／即將推出', 'credits.buyNotice': '購買點數目前僅提供展示模式。',
  'plans.title': '授權控制台', 'plans.preview': '價格預覽', 'plans.free': '免費', 'plans.creator': '創作者', 'plans.enterprise': '企業', 'plans.freeTagline': '探索 E.X Galaxy', 'plans.creatorTagline': '專為個人創作者與專業人士', 'plans.enterpriseTagline': '專為團隊與組織', 'plans.freePrice': '免費', 'plans.creatorPrice': '即將推出', 'plans.enterprisePrice': '聯絡洽詢', 'plans.current': '目前方案', 'plans.request': '申請存取', 'plans.contact': '聯絡企業方案',
  'plans.free.1': '基本銀河存取', 'plans.free.2': '展示模組', 'plans.free.3': '基本工作流', 'plans.free.4': '有限每月點數', 'plans.creator.1': '更高每月點數', 'plans.creator.2': '進階 AI 工作流', 'plans.creator.3': '高階 Video Studio', 'plans.creator.4': '未來雲端同步', 'plans.enterprise.1': '團隊工作區', 'plans.enterprise.2': '共享點數', 'plans.enterprise.3': '管理控制', 'plans.enterprise.4': '私有部署',
  'enterprise.title': '企業基礎層', 'enterprise.description': '為團隊、組織與自訂 AI 工作流準備的私有作業層。', 'enterprise.team': '團隊工作區', 'enterprise.sharedCredits': '共享點數', 'enterprise.admin': '組織管理', 'enterprise.roles': '權限角色', 'enterprise.workflow': '自訂 AI 工作流', 'enterprise.library': '私有素材庫', 'enterprise.api': 'API／整合', 'enterprise.deployment': '私有部署', 'enterprise.support': '專屬支援', 'enterprise.company': '公司', 'enterprise.name': '姓名', 'enterprise.email': '電子信箱', 'enterprise.teamSize': '團隊規模', 'enterprise.useCase': '使用情境', 'enterprise.submit': '聯絡企業方案', 'enterprise.captured': '需求已在展示模式中記錄。', 'enterprise.placeholderCompany': '組織名稱', 'enterprise.placeholderName': '顯示名稱', 'enterprise.placeholderEmail': 'name@company.com', 'enterprise.placeholderTeam': '例如：20–50 人', 'enterprise.placeholderUseCase': 'E.X Galaxy 如何協助團隊？', 'common.close': '關閉', 'common.comingSoon': '即將推出', 'common.demo': '展示模式', 'common.contact': '聯絡我們',
}
